#ifndef LITTLEDB_CONFIG_H
#define LITTLEDB_CONFIG_H

#ifndef LITTLEDB_USE_CRC
#define LITTLEDB_USE_CRC 1
#endif

#ifndef LITTLEDB_AUTO_COMPACT
#define LITTLEDB_AUTO_COMPACT 0
#endif

#ifndef LITTLEDB_AUTO_COMPACT_THRESHOLD
#define LITTLEDB_AUTO_COMPACT_THRESHOLD 25
#endif

#endif