#ifndef LITTLEDB_VERSION_H
#define LITTLEDB_VERSION_H

#define LITTLEDB_VERSION_MAJOR 5
#define LITTLEDB_VERSION_MINOR 0
#define LITTLEDB_VERSION_PATCH 0

#define LITTLEDB_VERSION_STRING "5.0.0"

#endif