name=LittleDB
version=5.0.0
author=LittleDB
maintainer=LittleDB
sentence=Lightweight database for ESP8266 LittleFS.
paragraph=Simple record database with CRC32, iterator, algorithms and automatic IDs.
category=Data Storage
url=https://github.com/
architectures=esp8266
includes=LittleDB.h